name: build

on:
  #push:
  #  branches:
  #    - master
  #schedule:
  #  - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:

      - name: Build
        run: |
          useradd -m user
          usermod -aG wheel user
          echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers
          pacman -Syu git --noconfirm
          chown user:user $(pwd)
          
          sudo -u user git clone https://aur.archlinux.org/linux-lts515.git
          cd linux-lts515
          
          sed -i 's/pkgname=("$pkgbase" "$pkgbase-headers" "$pkgbase-docs")/pkgname=("$pkgbase" "$pkgbase-headers")/g' PKGBUILD
          sed -i 's/make htmldocs all/make all/g' PKGBUILD
          
          echo "ver=$(cat PKGBUILD | grep pkgver= | cut -d "=" -f 2)" >> $GITHUB_ENV
          
          sudo -u user gpg --recv-keys 38DBBDC86092693E
          sudo -u user makepkg -s --noconfirm
          mv *.pkg.tar.zst ../
          cd ..
          
          repo-add linux-lts515-bin.db.tar.gz *.pkg.tar.zst
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.ver }}
          files: |
            ./*.pkg.tar.zst
            ./linux-lts515-bin.db*
            ./linux-lts515-bin.files*
